export { JS_LEVELS, type JavascriptLevelId } from './levels'

export const JS_LESSONS = [
  {
    id: 'syntax',
    level: 'basic',
    kicker: 'Базовый · урок 1',
    title: 'Синтаксис',
    lead: 'console.log, комментарии, кавычки, точка с запятой и регистр имён.',
    questions: [
      {
        question: 'Что выведет этот код?',
        context: 'Первый вывод в консоль',
        code: 'console.log("hello")',
        options: [
          'hello',
          '"hello"',
          'console.log("hello")',
          'Ошибку: log нельзя вызывать со строкой',
          'Ничего, console.log только считает значение',
        ],
        correct: 0,
        explanation: 'console.log печатает аргументы в консоль. Кавычки — синтаксис строки, на экран они не попадают: выведется hello.',
      },
      {
        question: 'Какая строка выполнится?',
        context: 'Комментарии',
        code: 'let x = 1 // x = 2\nconsole.log(x)',
        options: [
          'Выведет 1: текст после // не выполняется',
          'Выведет 2: комментарий перезапишет x',
          'Выведет 1 2',
          'Ошибка: // нельзя писать в той же строке',
          'Ничего не выведет: вся строка — комментарий',
        ],
        correct: 0,
        explanation: 'Однострочный комментарий начинается с // и идёт до конца строки. Присвоится x = 1, а x = 2 не выполнится.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Одинарные и двойные кавычки',
        code: 'const a = \'hi\'\nconst b = "hi"\nconsole.log(a === b)',
        options: [
          'true — обе записи создают одну и ту же строку',
          'false — одинарные и двойные кавычки это разные типы',
          'hi hi',
          'Ошибку: смешивать кавычки нельзя',
          '\'hi\' "hi"',
        ],
        correct: 0,
        explanation: 'И \'hi\', и "hi" — это string. === сравнивает содержимое, поэтому true.',
      },
      {
        question: 'Что произойдёт при запуске?',
        context: 'Регистр имён',
        code: 'Console.log("hi")',
        options: [
          'ReferenceError: Console ≠ console, имена чувствительны к регистру',
          'Выведет hi — регистр не важен',
          'Движок сам заменит Console на console',
          'Выведет HI заглавными',
          'Выведет Console.log("hi") как текст',
        ],
        correct: 0,
        explanation: 'console — объект глобальной среды. Console — другое имя, его нет, поэтому ReferenceError.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Несколько аргументов',
        code: 'console.log("cat", "dog")',
        options: [
          'cat dog',
          'catdog',
          'cat, dog',
          '("cat", "dog")',
          'Ошибку: log принимает только один аргумент',
        ],
        correct: 0,
        explanation: 'Несколько аргументов console.log печатает через пробел. Запятая в вызове — разделитель аргументов.',
      },
      {
        question: 'Нужна ли точка с запятой?',
        context: 'ASI — автоматическая вставка ;',
        code: 'const n = 1\nconsole.log(n)',
        options: [
          'Код валиден: движок сам вставит точку с запятой',
          'Ошибка: после const всегда нужна ;',
          'Выведет undefined',
          'Сработает только в строгом режиме',
          'console.log не выполнится',
        ],
        correct: 0,
        explanation: 'JavaScript вставляет точки с запятой сам (ASI). Их всё же полезно писать, чтобы не словить редкие ловушки с переносом строки.',
      },
    ],
  },
  {
    id: 'variables',
    level: 'basic',
    kicker: 'Базовый · урок 2',
    title: 'Переменные',
    lead: 'let, const, var: область видимости, переназначение и temporal dead zone.',
    questions: [
      {
        question: 'Что выведет этот код?',
        context: 'const нельзя переназначить',
        code: 'const n = 1\nn = 2',
        options: [
          'TypeError: константу нельзя переназначить',
          'Выведет 2',
          'Выведет 1, присваивание проигнорируется',
          'n станет undefined',
          'Ошибку только в strict mode, иначе 2',
        ],
        correct: 0,
        explanation: 'const запрещает повторное присваивание. Сам объект по ссылке менять можно, но не саму переменную.',
      },
      {
        question: 'Чем let отличается от var?',
        context: 'Область видимости',
        options: [
          'let — блочная область видимости, var — функциональная',
          'Ничем, это синонимы',
          'let нельзя использовать в циклах',
          'var работает только в модулях',
          'let всегда глобальная переменная',
        ],
        correct: 0,
        explanation: 'let и const живут в блоке { }. var видна во всей функции (или глобально) и всплывает.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Переназначение let',
        code: 'let x = 1\nx = 2\nconsole.log(x)',
        options: [
          '2',
          '1',
          'Ошибку: let нельзя менять',
          'undefined',
          '1 2',
        ],
        correct: 0,
        explanation: 'let можно переназначать. Нельзя только повторно объявить let x в той же области.',
      },
      {
        question: 'Почему этот код упадёт?',
        context: 'Обращение до объявления',
        code: 'console.log(x)\nlet x = 1',
        options: [
          'ReferenceError: let в temporal dead zone до строки объявления',
          'Выведет undefined, как с var',
          'Выведет 1: let всплывает со значением',
          'Выведет null',
          'Код валиден в браузере',
        ],
        correct: 0,
        explanation: 'let и const всплывают, но до объявления находятся в TDZ. Обращение раньше let даёт ReferenceError, а не undefined как у var.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'var всплывает',
        code: 'console.log(x)\nvar x = 1',
        options: [
          'undefined',
          '1',
          'ReferenceError',
          'null',
          'Ошибку синтаксиса',
        ],
        correct: 0,
        explanation: 'var всплывает: объявление есть с начала функции, значение присвоится позже. До присваивания переменная undefined.',
      },
      {
        question: 'Можно ли менять поля объекта в const?',
        context: 'const хранит ссылку',
        code: 'const user = { n: 1 }\nuser.n = 2\nconsole.log(user.n)',
        options: [
          '2 — const запрещает смену ссылки, не мутацию объекта',
          'TypeError: объект в const заморожен',
          '1, присваивание поля игнорируется',
          'undefined',
          'Ошибку только в strict mode',
        ],
        correct: 0,
        explanation: 'const user нельзя сделать другим объектом, но свойства user менять можно. Чтобы запретить мутацию, нужен Object.freeze.',
      },
    ],
  },
  {
    id: 'types',
    level: 'basic',
    kicker: 'Базовый · урок 3',
    title: 'Типы',
    lead: 'typeof, примитивы, == и ===, null и undefined, NaN.',
    questions: [
      {
        question: 'Что вернёт typeof null?',
        context: 'Старая ошибка языка',
        code: 'typeof null',
        options: [
          '"object" — историческая ошибка в языке',
          '"null"',
          '"undefined"',
          '"boolean"',
          'Ошибку: typeof не работает с null',
        ],
        correct: 0,
        explanation: 'typeof null === "object" — баг первых реализаций, который оставили ради совместимости. Проверяйте null через value === null.',
      },
      {
        question: 'Чем === отличается от ==?',
        context: 'Сравнение',
        options: [
          '=== не приводит типы, == приводит',
          'Ничем в современном JS',
          '=== сравнивает только числа',
          '== нельзя использовать со строками',
          '=== всегда медленнее',
        ],
        correct: 0,
        explanation: '1 == "1" — true из-за приведения. 1 === "1" — false. На собесе почти всегда ждут ===.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'undefined vs null',
        code: 'console.log(typeof undefined)\nconsole.log(typeof null)',
        options: [
          '"undefined" затем "object"',
          '"undefined" затем "null"',
          '"object" затем "object"',
          '"null" затем "null"',
          'Ошибку на второй строке',
        ],
        correct: 0,
        explanation: 'undefined — свой тип. null при typeof даёт "object". Значения разные: undefined — «нет значения», null — «сознательно пусто».',
      },
      {
        question: 'Что выведет этот код?',
        context: 'NaN',
        code: 'console.log(Number("abc"))\nconsole.log(Number.isNaN(Number("abc")))',
        options: [
          'NaN затем true',
          '0 затем false',
          'undefined затем true',
          'Ошибку: Number не принимает строки',
          'NaN затем false',
        ],
        correct: 0,
        explanation: 'Нечисловая строка даёт NaN. Сравнивать через x === NaN нельзя: NaN не равен сам себе. Нужен Number.isNaN.',
      },
      {
        question: 'Какие типы считает примитивами JS?',
        context: 'Примитивы',
        options: [
          'string, number, boolean, null, undefined, symbol, bigint',
          'Только string, number и boolean',
          'object и function тоже примитивы',
          'Только то, что возвращает typeof "object"',
          'array и date',
        ],
        correct: 0,
        explanation: 'Семь примитивов. Всё остальное — объекты (включая массивы и функции).',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Логическое приведение',
        code: 'console.log(Boolean(0))\nconsole.log(Boolean(""))\nconsole.log(Boolean([]))',
        options: [
          'false, false, true',
          'false, false, false',
          'true, false, true',
          'false, true, true',
          'Ошибку: Boolean не работает с массивами',
        ],
        correct: 0,
        explanation: 'Ложные значения: 0, "", null, undefined, NaN, false. Пустой массив — объект, он truthy.',
      },
    ],
  },
  {
    id: 'strings',
    level: 'basic',
    kicker: 'Базовый · урок 4',
    title: 'Строки',
    lead: 'Шаблонные строки, length, методы и неизменяемость.',
    questions: [
      {
        question: 'Что выведет этот код?',
        context: 'Шаблонные строки',
        code: 'const n = 3\nconsole.log(`cat ${n}`)',
        options: [
          'cat 3',
          'cat ${n}',
          'cat3',
          'Ошибку: внутри `` нельзя вставлять выражения',
          '"cat " + n как текст кода',
        ],
        correct: 0,
        explanation: 'В обратных кавычках ${...} подставляет значение. Это template literal.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'length',
        code: 'console.log("hi".length)',
        options: [
          '2',
          '3',
          '"2"',
          'undefined: у строк нет length',
          'Ошибку',
        ],
        correct: 0,
        explanation: 'У строки есть length — число символей UTF-16. "hi" — два символа.',
      },
      {
        question: 'Строки в JS изменяемые?',
        context: 'Иммутабельность',
        code: 'let s = "ab"\ns[0] = "z"\nconsole.log(s)',
        options: [
          '"ab" — строки нельзя менять по индексу',
          '"zb"',
          '"z"',
          'Ошибку в strict mode, иначе "zb"',
          'undefined',
        ],
        correct: 0,
        explanation: 'Строки неизменяемые. Присваивание s[0] ничего не делает (в strict mode может тихо проигнорироваться). Нужно собрать новую строку.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'slice',
        code: 'console.log("hello".slice(1, 4))',
        options: [
          'ell',
          'ello',
          'hell',
          'e',
          'Ошибку: slice только для массивов',
        ],
        correct: 0,
        explanation: 'slice(start, end) берёт символы с start включительно до end не включительно: индексы 1, 2, 3 → ell.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Конкатенация',
        code: 'console.log("2" + 1)\nconsole.log("2" - 1)',
        options: [
          '"21" затем 1',
          '3 затем 1',
          '"21" затем "21"',
          '3 затем "1"',
          'Ошибку на второй строке',
        ],
        correct: 0,
        explanation: '+ со строкой склеивает. - всегда приводит к числу: "2" - 1 → 1. Классический вопрос на собесе.',
      },
      {
        question: 'Как привести строку к числу надёжно?',
        context: 'Парсинг',
        options: [
          'Number("10") или parseInt("10", 10)',
          '+"10abc" всегда даст 10',
          'parseInt без второго аргумента всегда десятичный',
          'String(10) наоборот, из числа в строку — это одно и то же',
          'typeof "10" === "number"',
        ],
        correct: 0,
        explanation: 'Number("10") → 10, Number("10px") → NaN. parseInt("10px", 10) → 10, основание лучше указывать явно.',
      },
    ],
  },
  {
    id: 'arrays',
    level: 'basic',
    kicker: 'Базовый · урок 5',
    title: 'Массивы',
    lead: 'Индексы, push/pop, map, filter и ссылочная природа.',
    questions: [
      {
        question: 'Что выведет этот код?',
        context: 'Индексация с нуля',
        code: 'const a = ["a", "b", "c"]\nconsole.log(a[1])',
        options: [
          'b',
          'a',
          'c',
          '["b"]',
          'undefined',
        ],
        correct: 0,
        explanation: 'Индексы с нуля: 0 → a, 1 → b, 2 → c.',
      },
      {
        question: 'Что делает push?',
        context: 'Мутация массива',
        code: 'const a = [1]\na.push(2)\nconsole.log(a)',
        options: [
          '[1, 2]',
          '[2]',
          '[1]',
          '2 — push возвращает массив? Нет, он мутирует и возвращает длину',
          'Ошибку: const массив нельзя менять',
        ],
        correct: 0,
        explanation: 'push добавляет в конец и возвращает новую длину. const не мешает мутировать содержимое массива.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'map возвращает новый массив',
        code: 'const a = [1, 2]\nconst b = a.map(x => x * 2)\nconsole.log(b)\nconsole.log(a)',
        options: [
          '[2, 4] затем [1, 2]',
          '[2, 4] затем [2, 4]',
          '[1, 2] затем [1, 2]',
          'undefined затем [1, 2]',
          'Ошибку: стрелочная функция в map запрещена',
        ],
        correct: 0,
        explanation: 'map строит новый массив, исходный не меняет.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'filter',
        code: 'console.log([1, 2, 3, 4].filter(n => n % 2 === 0))',
        options: [
          '[2, 4]',
          '[1, 3]',
          '2 4',
          'true, false, true, false',
          '4',
        ],
        correct: 0,
        explanation: 'filter оставляет элементы, для которых колбэк вернул true. Чётные: 2 и 4.',
      },
      {
        question: 'Два массива с одним содержимым равны по ===?',
        context: 'Сравнение ссылок',
        code: 'console.log([1, 2] === [1, 2])',
        options: [
          'false — это два разных объекта',
          'true — содержимое одинаковое',
          'true только в strict mode',
          'Ошибку: массивы нельзя сравнивать',
          'false затем true при JSON.stringify',
        ],
        correct: 0,
        explanation: '=== для объектов сравнивает ссылку. Два литерала [1, 2] — два разных массива. Сравнивать содержимое нужно поэлементно.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'length можно менять',
        code: 'const a = [1, 2, 3]\na.length = 1\nconsole.log(a)',
        options: [
          '[1]',
          '[1, 2, 3]',
          '[1, 2]',
          'undefined',
          'Ошибку: length только для чтения',
        ],
        correct: 0,
        explanation: 'Запись в length обрезает или расширяет массив. length = 1 оставляет только первый элемент.',
      },
    ],
  },
  {
    id: 'objects',
    level: 'basic',
    kicker: 'Базовый · урок 6',
    title: 'Объекты',
    lead: 'Свойства, деструктуризация, ссылки и копирование.',
    questions: [
      {
        question: 'Как прочитать свойство?',
        context: 'Точка и скобки',
        code: 'const user = { name: "Ada" }\nconsole.log(user.name)\nconsole.log(user["name"])',
        options: [
          'Ada затем Ada',
          'Ada затем undefined',
          'undefined затем Ada',
          'Ошибку на второй строке',
          '{ name: "Ada" } дважды',
        ],
        correct: 0,
        explanation: 'Точка и скобки читают одно и то же. Скобки нужны, когда имя свойства в переменной.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Деструктуризация',
        code: 'const user = { name: "Ada" }\nconst { name, age } = user\nconsole.log(age)',
        options: [
          'undefined — поля age нет',
          'Ошибку: age обязательно',
          'null',
          '0',
          '"Ada"',
        ],
        correct: 0,
        explanation: 'Недостающее поле при деструктуризации даёт undefined. Можно задать значение по умолчанию: age = 0.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Копирование ссылки',
        code: 'const a = { n: 1 }\nconst b = a\nb.n = 2\nconsole.log(a.n)',
        options: [
          '2 — b и a один объект',
          '1 — присвоение копирует объект',
          'undefined',
          'Ошибку: нельзя менять через другую переменную',
          '{ n: 1 }',
        ],
        correct: 0,
        explanation: 'b = a копирует ссылку, не объект. Мутация через b видна в a. Поверхностная копия: { ...a } или Object.assign.',
      },
      {
        question: 'Что вернёт Object.keys?',
        context: 'Ключи объекта',
        code: 'Object.keys({ a: 1, b: 2 })',
        options: [
          '["a", "b"]',
          '[1, 2]',
          '["a: 1", "b: 2"]',
          '{ a: 1, b: 2 }',
          '2',
        ],
        correct: 0,
        explanation: 'Object.keys возвращает массив собственных перечисляемых ключей. Значения — Object.values, пары — Object.entries.',
      },
      {
        question: 'Есть ли у объекта свой length как у массива?',
        context: 'Не массив',
        code: 'console.log({ 0: "a", 1: "b" }.length)',
        options: [
          'undefined — обычный объект не считает индексы',
          '2',
          '1',
          '0',
          'Ошибку',
        ],
        correct: 0,
        explanation: 'length есть у массивов и строк. У объекта { 0, 1 } это просто ключи, не длина.',
      },
      {
        question: 'Что делает spread при копировании объекта?',
        context: 'Поверхностная копия',
        code: 'const a = { n: 1, nested: { x: 1 } }\nconst b = { ...a }\nb.nested.x = 2\nconsole.log(a.nested.x)',
        options: [
          '2 — вложенный объект тот же по ссылке',
          '1 — spread копирует всё глубоко',
          'undefined',
          'Ошибку: spread нельзя на вложенных',
          '{ x: 1 }',
        ],
        correct: 0,
        explanation: 'Spread копирует верхний уровень. Вложенные объекты остаются общими. Для глубокой копии — structuredClone или ручной обход.',
      },
    ],
  },
  {
    id: 'functions',
    level: 'basic',
    kicker: 'Базовый · урок 7',
    title: 'Функции',
    lead: 'Объявление, return, стрелки, параметры по умолчанию.',
    questions: [
      {
        question: 'Что выведет этот код?',
        context: 'return',
        code: 'function add(a, b) {\n  return a + b\n}\nconsole.log(add(2, 3))',
        options: [
          '5',
          'undefined',
          '2 3',
          'NaN',
          'Ошибку: return без ;',
        ],
        correct: 0,
        explanation: 'return отдаёт значение вызывающему коду. Без return функция вернёт undefined.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Нет return',
        code: 'function greet() {\n  console.log("hi")\n}\nconsole.log(greet())',
        options: [
          'hi затем undefined',
          'hi затем hi',
          'undefined затем hi',
          'Только hi',
          'Ошибку: нельзя печатать результат greet',
        ],
        correct: 0,
        explanation: 'Сначала выполнится console.log внутри, потом greet вернёт undefined — его напечатает внешний log.',
      },
      {
        question: 'Чем стрелочная функция отличается от function?',
        context: 'this и короткий синтаксис',
        options: [
          'У стрелки нет своего this, она берёт его снаружи',
          'Стрелка всегда async',
          'function нельзя передавать как колбэк',
          'Стрелку нельзя сохранить в переменную',
          'Ничем, кроме внешнего вида',
        ],
        correct: 0,
        explanation: 'У стрелочной функции нет своего this, arguments и конструктора. Удобна как колбэк, опасна как метод объекта.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Короткий return у стрелки',
        code: 'const double = x => x * 2\nconsole.log(double(4))',
        options: [
          '8',
          'undefined — нет return',
          'x * 2',
          '4',
          'Ошибку: нужны скобки (x) =>',
        ],
        correct: 0,
        explanation: 'Без фигурных скобок стрелка неявно возвращает выражение. С { } нужен return.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Параметр по умолчанию',
        code: 'function hi(name = "guest") {\n  return name\n}\nconsole.log(hi())\nconsole.log(hi("Ada"))',
        options: [
          'guest затем Ada',
          'undefined затем Ada',
          'guest затем guest',
          'Ошибку: аргумент обязателен',
          'null затем Ada',
        ],
        correct: 0,
        explanation: 'Если аргумент не передали (или передали undefined), сработает значение по умолчанию.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'Всплытие function declaration',
        code: 'console.log(sum(1, 2))\nfunction sum(a, b) {\n  return a + b\n}',
        options: [
          '3 — объявление функции всплывает целиком',
          'ReferenceError: sum ещё нет',
          'undefined',
          'Ошибку: вызов только после объявления',
          'NaN',
        ],
        correct: 0,
        explanation: 'Function declaration всплывает, её можно вызвать выше по коду. Function expression и const sum = () => {} — нет.',
      },
    ],
  },
  {
    id: 'interview',
    level: 'basic',
    kicker: 'Базовый · урок 8',
    title: 'Собеседование',
    lead: 'Типичные вопросы junior-собеседования: this, замыкание, ==, массив и копия.',
    questions: [
      {
        question: 'Что такое замыкание (closure)?',
        context: 'Фундаментальная концепция JS',
        options: [
          'Функция запоминает лексическое окружение, даже когда внешняя уже выполнилась',
          'Ошибка, когда переменная не объявлена',
          'Способ закрыть вкладку в браузере',
          'Механизм сборки мусора в V8',
          'Синтаксис приватных полей класса',
        ],
        correct: 0,
        explanation: 'Замыкание — функция плюс её лексическое окружение. Так делают приватные переменные и колбэки с состоянием.',
      },
      {
        question: 'Что такое this в обычной функции-методе?',
        context: 'Контекст вызова',
        options: [
          'Ссылка на объект, из которого вызвали метод',
          'Всегда глобальный объект',
          'Переменная, которую нужно объявить',
          'Всегда window, даже в классах',
          'Ключевое слово только для стрелок',
        ],
        correct: 0,
        explanation: 'У function this зависит от вызова: obj.method() → obj. У стрелки this снаружи. На собесе ждут разницу.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'this у стрелки в объекте',
        code: 'const obj = {\n  name: "Ada",\n  getName: () => this.name,\n}\nconsole.log(obj.getName())',
        options: [
          'undefined — у стрелки нет своего this',
          '"Ada"',
          'Ошибку: стрелку нельзя класть в объект',
          'window',
          '"getName"',
        ],
        correct: 0,
        explanation: 'Стрелка берёт this снаружи объекта (часто undefined в модуле). Для метода нужна обычная function или краткая запись getName() { return this.name }.',
      },
      {
        question: 'Что выведет этот код?',
        context: 'var в цикле и замыкание',
        code: 'for (var i = 0; i < 3; i++) {}\nconsole.log(i)',
        options: [
          '3 — var видна за пределами цикла',
          '2',
          '0',
          'ReferenceError: i не существует снаружи',
          'undefined',
        ],
        correct: 0,
        explanation: 'var не ограничена блоком for, после цикла i === 3. С let i снаружи цикла не будет видно.',
      },
      {
        question: 'Как скопировать массив, не деля ссылку?',
        context: 'Копия vs ссылка',
        options: [
          'a.slice() или [...a] — поверхностная копия',
          'b = a достаточно',
          'a.push копирует массив',
          'const b = a всегда новая копия',
          'JSON.stringify единственный способ',
        ],
        correct: 0,
        explanation: 'b = a — одна ссылка. slice и spread копируют верхний уровень. Вложенные объекты по-прежнему общие.',
      },
      {
        question: 'Что такое Event Loop простыми словами?',
        context: 'Асинхронность',
        options: [
          'Цикл, который забирает задачи из очереди, когда стек пуст',
          'Цикл for для массивов',
          'Способ обработки синтаксических ошибок',
          'Планировщик CSS-анимаций',
          'API только для WebSocket',
        ],
        correct: 0,
        explanation: 'JS однопоточный. setTimeout и промисы кладут колбэки в очереди. Event loop забирает их, когда синхронный код закончился. Сначала микротаски (промисы), потом макротаски (таймеры).',
      },
    ],
  },
]
