export const SITE_NAV = [
  {
    to: '/',
    label: 'Главная',
    key: 'home',
    eyebrow: 'Портфолио',
  },
  {
    to: '/services',
    label: 'Услуги',
    key: 'services',
    eyebrow: 'Услуги',
    lead: 'Реализую проекты любой сложности и направления — от лёгкого одностраничника до сложного SPA.',
    seoTitle: 'Услуги — Александр Обухов · Frontend-разработчик (Senior)',
    seoDescription: 'Frontend-разработчик (Senior): лендинги, каталоги, SPA и продукты на Vue 3 / Nuxt / TypeScript. Портфолио, GitHub и GitLab.',
  },
  {
    to: '/articles',
    label: 'Статьи',
    key: 'articles',
    eyebrow: 'Статьи',
    lead: 'Заметки о карьере в IT, обучении и практике разработки — без воды, с акцентом на то, что реально помогает расти.',
    seoTitle: 'Статьи — Александр Обухов',
    seoDescription: 'Заметки о карьере в IT, обучении и практике разработки — без воды, с акцентом на то, что реально помогает расти.',
  },
  {
    to: '/projects',
    label: 'Проекты',
    key: 'projects',
    eyebrow: 'Проекты',
    lead: 'Собственные продукты — от архитектуры и кода до деплоя.',
    seoTitle: 'Проекты — Александр Обухов',
    seoDescription: 'Текущие проекты CodeVega и Codestats.',
  },
  {
    to: '/resume',
    label: 'Резюме',
    key: 'resume',
    eyebrow: 'Резюме',
  },
  {
    to: '/projects/portfolio',
    label: 'Портфолио',
    key: 'portfolio',
    eyebrow: 'Проекты',
    lead: 'Портфолио — код на GitLab или GitHub, плюс живые демо.',
    seoTitle: 'Портфолио — Александр Обухов',
    seoDescription: 'Портфолио: pet-проекты, живые демо и код на GitLab или GitHub.',
  },
  {
    to: '/motivation',
    label: 'Мотивация',
    key: 'motivation',
    eyebrow: 'Мотивация',
    lead: 'Интерактивная история о росте в IT — от диплома до Senior, с юмором, багами и правильными выводами.',
    seoTitle: 'Мотивация — Путь IT-специалиста · Александр Обухов',
    seoDescription: 'Интерактивная история о пути IT-специалиста — от диплома до Senior.',
  },
  {
    to: '/trainers',
    label: 'Тренажёры',
    key: 'trainers',
    eyebrow: 'Тренажёры',
    lead: 'Небольшие интерактивные тренажёры для практики.',
    seoTitle: 'Тренажёры — Александр Обухов',
    seoDescription: 'Интерактивные тренажёры: слепая печать, собеседования по Python и JavaScript, поиск багов.',
  },
] as const
