export const SITE_NAV = [
  {
    to: '/',
    label: 'Главная',
    key: 'home',
    eyebrow: 'Портфолио',
  },
  {
    to: '/services',
    label: 'Услуги',
    key: 'services',
    eyebrow: 'Услуги',
    lead: 'Vue 3 / Nuxt и Node.js — от интерфейса и API до деплоя.',
    seoTitle: 'Услуги — Александр Обухов',
    seoDescription: 'Frontend, backend и DevOps под ключ. Vue, Nuxt, Node.js — от идеи до продакшена.',
  },
  {
    to: '/articles',
    label: 'Статьи',
    key: 'articles',
    eyebrow: 'Статьи',
    lead: 'Заметки о карьере в IT, обучении и практике разработки — без воды, с акцентом на то, что реально помогает расти.',
    seoTitle: 'Статьи — Александр Обухов',
    seoDescription: 'Заметки о карьере в IT, обучении и практике разработки — без воды, с акцентом на то, что реально помогает расти.',
  },
  {
    to: '/projects',
    label: 'Проекты',
    key: 'projects',
    eyebrow: 'Проекты',
    lead: 'Собственные продукты в разработке — от архитектуры и кода до деплоя.',
    seoTitle: 'Проекты — Александр Обухов',
    seoDescription: 'Текущие проекты: LearnPortal и Codestats — от архитектуры и кода до деплоя.',
  },
  {
    to: '/resume',
    label: 'Резюме',
    key: 'resume',
    eyebrow: 'Резюме',
  },
  {
    to: '/motivation',
    label: 'Мотивация',
    key: 'motivation',
    eyebrow: 'Мотивация',
    lead: 'Интерактивная история о росте в IT — от диплома до Senior, с юмором, багами и правильными выводами.',
    seoTitle: 'Мотивация — Путь IT-специалиста · Александр Обухов',
    seoDescription: 'Интерактивная история о росте в IT — от диплома до Senior, с юмором, багами и правильными выводами.',
  },
  {
    to: '/trainers',
    label: 'Тренажёры',
    key: 'trainers',
    eyebrow: 'Тренажёры',
    lead: 'Небольшие интерактивные тренажёры для практики. Пока два: слепая печать и базовый Python.',
    seoTitle: 'Тренажёры — Александр Обухов',
    seoDescription: 'Интерактивные тренажёры: слепая печать Touch Type и квиз по Python.',
  },
  {
    to: '/ai',
    label: 'ИИ',
    key: 'ai',
    eyebrow: 'ИИ',
    lead: 'Сравнивай модели, бенчмарки и цены. Быстро находи лучшее под свои задачи.',
    seoTitle: 'Рейтинг нейросетей — Александр Обухов',
    seoDescription: 'Сравнивай модели, бенчмарки и цены. Быстро находи лучшее под свои задачи.',
  },
] as const
