import type { BugItem } from './bugs'

export const JAVASCRIPT_BUGS: BugItem[] = [
  {
    level: 'junior',
    code: `function sum(a, b) {\n  return a + b;\n}\n\nconsole.log(sum(5, '3')); // 53 ???`,
    hint: 'Посмотри на типы данных',
    options: [
      'Нет проверки типов — при передаче строки произойдёт конкатенация',
      'Не хватает точки с запятой',
      'Функция не объявлена правильно',
      'console.log нельзя вызывать с результатом функции',
      'Строка "3" автоматически станет числом 3',
    ],
    correct: 0,
    explanation: 'При передаче строки (sum(5, "3")) оператор + выполняет конкатенацию, а не сложение. Нужно приводить типы: Number(a) + Number(b) или использовать parseInt.',
  },
  {
    level: 'junior',
    code: `const user = {\n  name: 'John',\n  age: 30\n};\n\nconst { name, age, city } = user;\nconsole.log(city); // undefined`,
    hint: 'Посмотри на деструктуризацию',
    options: [
      'В объекте user нет поля city — оно undefined',
      'Ошибка в синтаксисе деструктуризации',
      'city — зарезервированное слово',
      'name и age нельзя деструктурировать вместе',
      'console.log игнорирует undefined',
    ],
    correct: 0,
    explanation: 'При деструктуризации поля, которого нет в объекте, переменная получает значение undefined. Нужно либо добавить city в объект, либо задать значение по умолчанию: city = "Unknown".',
  },
  {
    level: 'junior',
    code: `let x = 10;\nlet y = '10';\n\nif (x == y) {\n  console.log('Equal!');\n} // "Equal!"`,
    hint: 'Посмотри на оператор сравнения',
    options: [
      'Используется == вместо ===, поэтому типы приводятся и значения считаются равными',
      'Синтаксическая ошибка в if',
      'Переменные объявлены неверно',
      'Строка "10" никогда не равна числу 10',
      'console.log внутри if запрещён',
    ],
    correct: 0,
    explanation: '== приводит типы (10 == "10" → true). Для строгого сравнения без приведения типов используйте ===.',
  },
  {
    level: 'junior',
    code: `const arr = [1, 2, 3];\narr.length = 0;\nconsole.log(arr); // []`,
    hint: 'Что происходит с arr?',
    options: [
      'Установка length = 0 очищает массив — это валидное поведение',
      'Ошибка: length нельзя изменять',
      'Массив станет undefined',
      'Элементы останутся, изменится только свойство length',
      'const запрещает менять length',
    ],
    correct: 0,
    explanation: 'В JavaScript length — это свойство массива, которое можно изменять. arr.length = 0 удаляет все элементы. Хитрый способ очистить массив без создания нового.',
  },
  {
    level: 'middle',
    code: `const numbers = [1, 2, 3, 4, 5];\n\nfor (var i = 0; i < numbers.length; i++) {\n  setTimeout(() => {\n    console.log(numbers[i]);\n  }, 100);\n}\n// undefined x5`,
    hint: 'Подумай о замыканиях и var',
    options: [
      'var имеет функциональную область видимости, i после цикла равна 5, поэтому numbers[5] = undefined',
      'Ошибка в синтаксисе setTimeout',
      'numbers — не массив',
      'setTimeout всегда игнорирует замыкания',
      'Индекс i замораживается на 0 во всех колбэках',
    ],
    correct: 0,
    explanation: 'var i имеет функциональную область видимости. К моменту выполнения setTimeout i уже равна 5. Решение: использовать let вместо var или IIFE.',
  },
  {
    level: 'middle',
    code: `const obj = {\n  name: 'Alice',\n  getName: () => {\n    return this.name;\n  }\n};\n\nconsole.log(obj.getName()); // undefined`,
    hint: 'Что такое this в стрелочной функции?',
    options: [
      'Стрелочные функции не имеют своего this, они берут его из внешнего контекста',
      'Ошибка в объявлении объекта',
      'name — приватное поле',
      'Методы объекта нельзя вызывать через точку',
      'this всегда указывает на obj внутри методов',
    ],
    correct: 0,
    explanation: 'Стрелочные функции не имеют собственного this, они наследуют его из внешней области. Решение: использовать обычную function() { return this.name; }.',
  },
  {
    level: 'middle',
    code: `const promise = new Promise((resolve, reject) => {\n  setTimeout(() => {\n    reject(new Error('Oops!'));\n  }, 1000);\n});\n\n// Никаких .catch()!`,
    hint: 'Где обработка ошибок?',
    options: [
      'Нет .catch() — будет Unhandled Promise Rejection',
      'Ошибка в setTimeout',
      'Promise создан неверно',
      'reject нельзя вызывать внутри setTimeout',
      'Ошибки Promise всегда игнорируются безопасно',
    ],
    correct: 0,
    explanation: 'Если у Promise нет обработчика .catch(), при reject возникает Unhandled Promise Rejection. Всегда добавляйте .catch() или используйте try/catch с async/await.',
  },
  {
    level: 'middle',
    code: `const data = [1, 2, 3, 4, 5];\n\nconst doubled = data.map(x => {\n  x * 2;\n});\n\nconsole.log(doubled); // [undefined, undefined, ...]`,
    hint: 'Что возвращает стрелочная функция?',
    options: [
      'Нет return — функция возвращает undefined. Нужно x => x * 2 или { return x * 2; }',
      'Ошибка в map',
      'data — не массив',
      'map всегда возвращает исходный массив',
      'x * 2 выполняется, но map его скрывает',
    ],
    correct: 0,
    explanation: 'Если тело стрелочной функции в {} и без return, она возвращает undefined. Решение: x => x * 2 или (x) => { return x * 2; }.',
  },
  {
    level: 'senior',
    code: `// Vue 3 <script setup>\nconst state = reactive({ count: 0 })\nconst { count } = state\n\nfunction inc() {\n  count++\n}\n\n// template: {{ count }}`,
    hint: 'Что будет с реактивностью после деструктуризации?',
    options: [
      'Деструктуризация reactive даёт обычное число: count++ не обновит шаблон. Нужны toRefs(state) или state.count++',
      'count останется реактивным — Vue отслеживает любые переменные',
      'Будет ошибка компиляции',
      'reactive нельзя деструктурировать синтаксически',
      'inc() обновит шаблон, потому что count++ мутирует state',
    ],
    correct: 0,
    explanation: 'reactive возвращает прокси. После const { count } = state это уже примитив, связь с прокси теряется. toRefs(state) сохраняет рефы, либо пишите state.count++.',
  },
  {
    level: 'senior',
    code: `// Асинхронный код\nasync function fetchData() {\n  const response = await fetch('/api/data');\n  const data = response.json();\n  return data;\n}`,
    hint: 'Посмотри на response.json()',
    options: [
      'Нет await перед response.json() — это возвращает Promise, а не данные',
      'Ошибка в синтаксисе async/await',
      'fetch не работает с /api/data',
      'response.json() всегда синхронный',
      'async функции не могут возвращать данные',
    ],
    correct: 0,
    explanation: 'response.json() возвращает Promise. Без await мы получаем Promise, а не данные. Нужно: const data = await response.json();',
  },
  {
    level: 'senior',
    code: `// Vue 3\nconst user = reactive({\n  name: 'Ann',\n  city: 'Moscow',\n})\n\nwatch(user, () => {\n  console.log('user changed')\n})\n\nuser.city = 'SPb'`,
    hint: 'Сработает ли watch?',
    options: [
      'По умолчанию watch на объекте не глубокий — смена user.city не вызовет колбэк. Нужен { deep: true }',
      'Любое поле reactive всегда триггерит watch',
      'Ошибка: watch нельзя вызывать на reactive',
      'Колбэк сработает один раз при создании user',
      'user.city = "SPb" заменит весь объект, поэтому watch сработает',
    ],
    correct: 0,
    explanation: 'watch(объект) без deep следит за заменой ссылки, не за полями. Для вложенных изменений: watch(user, fn, { deep: true }) или watch(() => user.city, fn).',
  },
  {
    level: 'senior',
    code: `// Vue 3 <script setup>\nconst props = defineProps({\n  items: { type: Array, required: true },\n})\n\nfunction add(item) {\n  props.items.push(item)\n}`,
    hint: 'Можно ли менять props в дочернем компоненте?',
    options: [
      'Мутация props.items ломает односторонний поток данных. Нужен emit или локальная копия',
      'push у props в Vue 3 всегда безопасен и рекомендуется',
      'defineProps нельзя вызывать в script setup',
      'Массивы в props заморожены, push тихо ничего не сделает',
      'Vue сам скопирует items, родитель не изменится',
    ],
    correct: 0,
    explanation: 'Пропсы только для чтения. push мутирует массив родителя и усложняет отладку. Правильно: emit("add", item) или свой ref([...props.items]).',
  },
  {
    level: 'expert',
    code: `<!-- Vue 3 -->\n<li\n  v-for="user in users"\n  v-if="user.active"\n  :key="user.id"\n>\n  {{ user.name }}\n</li>`,
    hint: 'Какой директиве Vue отдаст приоритет?',
    options: [
      'На одном элементе v-if выше v-for: user ещё не определён, список сломается. Фильтруйте в computed или оберните template',
      'v-for всегда выполняется первым, это валидный и рекомендуемый код',
      ':key нельзя ставить вместе с v-for',
      'v-if на li просто скроет неактивных, как v-show',
      'Vue 3 запрещает v-for на li, только на template',
    ],
    correct: 0,
    explanation: 'В Vue 3 на одном узле v-if приоритетнее v-for, поэтому user в условии не существует. Сделайте activeUsers computed или <template v-for> + внутренний v-if.',
  },
  {
    level: 'expert',
    code: `// Event Loop\nconsole.log('1');\n\nsetTimeout(() => console.log('2'), 0);\n\nPromise.resolve().then(() => console.log('3'));\n\nconsole.log('4');\n\n// Какой порядок?`,
    hint: 'Помни про микротаски и макротаски',
    options: [
      '1, 4, 3, 2 — сначала синхронный код, затем микротаски, затем макротаски',
      '1, 2, 3, 4',
      '1, 4, 2, 3',
      '1, 3, 4, 2',
      '4, 1, 3, 2',
    ],
    correct: 0,
    explanation: 'Сначала синхронный код (1, 4), затем микротаски (Promise — 3), затем макротаски (setTimeout — 2).',
  },
]
