import type { BugItem } from './bugs'

export const PYTHON_BUGS: BugItem[] = [
  {
    level: 'junior',
    code: `def add(a, b):\n    return a + b\n\nprint(add(5, '3'))`,
    hint: 'Посмотри на типы аргументов',
    options: [
      'int и str нельзя сложить — будет TypeError. Нужно привести типы',
      'Python сам превратит "3" в число 3',
      'Не хватает двоеточия после return',
      'print нельзя вызывать с результатом функции',
      'Функция add объявлена неверно',
    ],
    correct: 0,
    explanation: 'Оператор + для int и str в Python не приводит типы, а выбрасывает TypeError. Нужно int(b) или заранее проверять типы.',
  },
  {
    level: 'junior',
    code: `user = {'name': 'John', 'age': 30}\nprint(user['city'])`,
    hint: 'Посмотри на ключи словаря',
    options: [
      'Ключа city нет — будет KeyError. Безопаснее user.get("city")',
      'Синтаксическая ошибка в словаре',
      'city — зарезервированное слово',
      'print игнорирует отсутствующие ключи и печатает None',
      'К словарю нельзя обращаться через []',
    ],
    correct: 0,
    explanation: 'user["city"] бросает KeyError, если ключа нет. user.get("city") вернёт None, можно задать значение по умолчанию.',
  },
  {
    level: 'junior',
    code: `a = [1, 2]\nb = [1, 2]\nprint(a == b)\nprint(a is b)`,
    hint: 'Чем is отличается от ==',
    options: [
      '== сравнивает содержимое (True), is — один ли это объект (False)',
      'is и == для списков всегда дают одно и то же',
      'a is b будет True, потому что значения одинаковые',
      '== для списков запрещён',
      'print печатает только первое сравнение',
    ],
    correct: 0,
    explanation: '== смотрит на равенство значений, is — на идентичность объекта в памяти. Два списка [1, 2] равны, но это разные объекты.',
  },
  {
    level: 'junior',
    code: `xs = [1, 2, 3]\nys = xs\nys.append(4)\nprint(xs)`,
    hint: 'Сколько списков здесь на самом деле?',
    options: [
      'ys = xs не копирует список — оба имени ссылаются на один объект, xs тоже станет [1, 2, 3, 4]',
      'xs останется [1, 2, 3], меняется только ys',
      'append нельзя вызывать у списка',
      'Присваивание ys = xs создаёт глубокую копию',
      'print(xs) выведет ошибку',
    ],
    correct: 0,
    explanation: 'Присваивание копирует ссылку, не данные. Чтобы получить независимый список: ys = xs.copy() или ys = xs[:].',
  },
  {
    level: 'middle',
    code: `fns = []\nfor i in range(3):\n    fns.append(lambda: i)\nprint([f() for f in fns])`,
    hint: 'Когда lambda смотрит на i',
    options: [
      'Все лямбды читают одну переменную i — после цикла она равна 2, поэтому [2, 2, 2]',
      'Будет [0, 1, 2], потому что i захватывается сразу',
      'Синтаксическая ошибка в lambda',
      'range(3) нельзя использовать в цикле с lambda',
      'Вызов f() запрещён внутри list comprehension',
    ],
    correct: 0,
    explanation: 'Замыкание берёт i по имени, а не по значению на момент создания. Фикс: lambda i=i: i или использовать значение по умолчанию.',
  },
  {
    level: 'middle',
    code: `nums = [1, 2, 3, 4]\nfor n in nums:\n    if n % 2 == 0:\n        nums.remove(n)\nprint(nums)`,
    hint: 'Что будет, если менять список во время обхода',
    options: [
      'Мутация во время for пропускает элементы — результат не [1, 3], а например [1, 3, 4]',
      'remove во время цикла всегда безопасен',
      'nums станет пустым',
      'for по списку копирует его автоматически',
      'Будет SyntaxError',
    ],
    correct: 0,
    explanation: 'После remove индексы сдвигаются, и for перескакивает следующий элемент. Обходите копию: for n in nums[:]: или собирайте новый список.',
  },
  {
    level: 'middle',
    code: `import copy\na = {'x': [1, 2]}\nb = copy.copy(a)\nb['x'].append(3)\nprint(a['x'])`,
    hint: 'copy.copy — это какая копия?',
    options: [
      'copy.copy поверхностная: вложенный список общий, a["x"] тоже станет [1, 2, 3]',
      'copy.copy делает глубокую копию, a не изменится',
      'append нельзя вызывать у списка внутри словаря',
      'copy.copy копирует только ключи, не значения',
      'Будет KeyError по ключу x',
    ],
    correct: 0,
    explanation: 'Поверхностная копия дублирует только верхний словарь. Вложенный список один на двоих. Для независимости нужен copy.deepcopy.',
  },
  {
    level: 'middle',
    code: `items = ['a', 'b', 'c']\nprint(items[3])`,
    hint: 'Какой индекс последний',
    options: [
      'Индекс 3 за границей — IndexError. Последний элемент items[2] или items[-1]',
      'items[3] вернёт None',
      'Python замкнёт индекс и вернёт items[0]',
      'Списки расширяются сами, если индекс больше длины',
      'print проигнорирует ошибку и ничего не выведет',
    ],
    correct: 0,
    explanation: 'В Python выход за границу списка — IndexError, а не undefined как в JS. Длина 3, валидные индексы 0, 1, 2.',
  },
  {
    level: 'senior',
    code: `def add_item(item, bag=[]):\n    bag.append(item)\n    return bag\n\nprint(add_item(1))\nprint(add_item(2))`,
    hint: 'Что случится со значением по умолчанию',
    options: [
      'Мутабельный bag=[] создаётся один раз — второй вызов вернёт [1, 2], а не [2]',
      'Каждый вызов получает новый пустой список',
      'append нельзя использовать как значение по умолчанию',
      'Второй print выведет [2]',
      'Будет SyntaxError из-за bag=[]',
    ],
    correct: 0,
    explanation: 'Значение по умолчанию вычисляется один раз при определении функции. Нужно bag=None и внутри bag = [] if bag is None else bag.',
  },
  {
    level: 'senior',
    code: `class User:\n    tags = []\n    def add(self, tag):\n        self.tags.append(tag)\n\nu1, u2 = User(), User()\nu1.add('a')\nprint(u2.tags)`,
    hint: 'Чей это список tags',
    options: [
      'tags — атрибут класса, общий для всех экземпляров: u2.tags тоже ["a"]',
      'У каждого экземпляра свой tags, u2.tags будет []',
      'append на атрибуте класса запрещён',
      'u2.tags вызовет AttributeError',
      'self.tags всегда создаёт новый список',
    ],
    correct: 0,
    explanation: 'Мутабельный атрибут класса один на всех. Нужно задавать self.tags = [] в __init__.',
  },
  {
    level: 'senior',
    code: `async def load():\n    return {'ok': True}\n\ndef main():\n    data = load()\n    print(data['ok'])`,
    hint: 'Что возвращает async def без await',
    options: [
      'load() возвращает корутину, не словарь — будет TypeError. Нужен await load()',
      'async функции вызываются как обычные и сразу отдают dict',
      'data["ok"] напечатает True',
      'await можно писать только внутри def, не async def',
      'print сам развернёт корутину',
    ],
    correct: 0,
    explanation: 'Вызов async-функции даёт coroutine object. Чтобы получить словарь: data = await load() внутри другой async-функции или asyncio.run.',
  },
  {
    level: 'senior',
    code: `def gen():\n    yield 1\n    yield 2\n\ng = gen()\nprint(list(g))\nprint(list(g))`,
    hint: 'Можно ли обойти генератор дважды',
    options: [
      'Генератор одноразовый: второй list(g) даст []',
      'Оба print выведут [1, 2]',
      'Второй вызов list(g) перезапустит gen()',
      'yield нельзя использовать два раза в одной функции',
      'Будет StopIteration на первом list(g)',
    ],
    correct: 0,
    explanation: 'Итератор генератора исчерпывается. Для повторного обхода нужно снова вызвать gen() или сохранить результат в список.',
  },
  {
    level: 'expert',
    code: `print(0.1 + 0.2 == 0.3)`,
    hint: 'Как хранятся вещественные числа',
    options: [
      'False: двоичная float-арифметика не даёт точное 0.3, сравнивайте с допуском или decimal',
      'True — сложение float всегда точное',
      'Будет TypeError',
      '== для float запрещён',
      'Python округлит сумму до 0.3 автоматически',
    ],
    correct: 0,
    explanation: '0.1 и 0.2 не представимы точно в IEEE-754, сумма чуть больше 0.3. Для денег и точных сравнений — decimal.Decimal или math.isclose.',
  },
  {
    level: 'expert',
    code: `import threading\n\nx = 0\n\ndef bump():\n    global x\n    for _ in range(100_000):\n        x += 1\n\nthreads = [threading.Thread(target=bump) for _ in range(2)]\nfor t in threads:\n    t.start()\nfor t in threads:\n    t.join()\nprint(x)`,
    hint: 'x += 1 — это одна операция?',
    options: [
      'Не обязательно 200000: x += 1 не атомарна, два потока гоняются за одним x',
      'GIL гарантирует, что print(x) всегда 200000',
      'threading нельзя использовать с global',
      'join запрещён после start',
      'range с подчёркиванием 100_000 — синтаксическая ошибка',
    ],
    correct: 0,
    explanation: 'GIL не делает составное присваивание атомарным: чтение-сложение-запись могут переплестись. Для счётчика нужен Lock или queue.',
  },
]
